bin/cake bake all Status -f
bin/cake bake all PeopleType -f
bin/cake bake all DocumentsType -f
bin/cake bake all People -f
bin/cake bake all Login -f
bin/cake bake all Services -f
bin/cake bake all Demands -f
bin/cake bake all Departments -f
bin/cake bake all Documents -f
bin/cake bake all History -f
bin/cake bake all Messages -f
bin/cake bake all Payments -f
bin/cake bake all PeopleServices -f
bin/cake bake all Requirements -f
bin/cake bake all Tags -f
